modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "GPLv3"

[[mods]]
modId = "exstrangefoodreborn"
version = "${version}"
displayName = "ExSF Reborn"
authors = '''
MCTeamPotato
Awei
'''
description = '''
ExStrangeFoodReborn Mod!
'''
#logoFile = ""

[[dependencies.exstrangefoodreborn]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.exstrangefoodreborn]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.exstrangefoodreborn]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.77,)"
ordering = "AFTER"
side = "BOTH"