name: build-ci
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build artifacts
        run: ./gradlew build
      - name: Capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build Artifacts
          path: |
            fabric/build/libs/*.jar
            forge/build/libs/*.jar